/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TShowGrantRoleParams implements org.apache.thrift.TBase<TShowGrantRoleParams, TShowGrantRoleParams._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TShowGrantRoleParams");

  private static final org.apache.thrift.protocol.TField REQUESTING_USER_FIELD_DESC = new org.apache.thrift.protocol.TField("requesting_user", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ROLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("role_name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField IS_ADMIN_OP_FIELD_DESC = new org.apache.thrift.protocol.TField("is_admin_op", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField PRIVILEGE_FIELD_DESC = new org.apache.thrift.protocol.TField("privilege", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TShowGrantRoleParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TShowGrantRoleParamsTupleSchemeFactory());
  }

  public String requesting_user; // optional
  public String role_name; // required
  public boolean is_admin_op; // required
  public com.cloudera.impala.thrift.TPrivilege privilege; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REQUESTING_USER((short)1, "requesting_user"),
    ROLE_NAME((short)2, "role_name"),
    IS_ADMIN_OP((short)3, "is_admin_op"),
    PRIVILEGE((short)4, "privilege");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REQUESTING_USER
          return REQUESTING_USER;
        case 2: // ROLE_NAME
          return ROLE_NAME;
        case 3: // IS_ADMIN_OP
          return IS_ADMIN_OP;
        case 4: // PRIVILEGE
          return PRIVILEGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_ADMIN_OP_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.REQUESTING_USER,_Fields.PRIVILEGE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REQUESTING_USER, new org.apache.thrift.meta_data.FieldMetaData("requesting_user", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("role_name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_ADMIN_OP, new org.apache.thrift.meta_data.FieldMetaData("is_admin_op", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.PRIVILEGE, new org.apache.thrift.meta_data.FieldMetaData("privilege", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.cloudera.impala.thrift.TPrivilege.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TShowGrantRoleParams.class, metaDataMap);
  }

  public TShowGrantRoleParams() {
  }

  public TShowGrantRoleParams(
    String role_name,
    boolean is_admin_op)
  {
    this();
    this.role_name = role_name;
    this.is_admin_op = is_admin_op;
    setIs_admin_opIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TShowGrantRoleParams(TShowGrantRoleParams other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetRequesting_user()) {
      this.requesting_user = other.requesting_user;
    }
    if (other.isSetRole_name()) {
      this.role_name = other.role_name;
    }
    this.is_admin_op = other.is_admin_op;
    if (other.isSetPrivilege()) {
      this.privilege = new com.cloudera.impala.thrift.TPrivilege(other.privilege);
    }
  }

  public TShowGrantRoleParams deepCopy() {
    return new TShowGrantRoleParams(this);
  }

  @Override
  public void clear() {
    this.requesting_user = null;
    this.role_name = null;
    setIs_admin_opIsSet(false);
    this.is_admin_op = false;
    this.privilege = null;
  }

  public String getRequesting_user() {
    return this.requesting_user;
  }

  public TShowGrantRoleParams setRequesting_user(String requesting_user) {
    this.requesting_user = requesting_user;
    return this;
  }

  public void unsetRequesting_user() {
    this.requesting_user = null;
  }

  /** Returns true if field requesting_user is set (has been assigned a value) and false otherwise */
  public boolean isSetRequesting_user() {
    return this.requesting_user != null;
  }

  public void setRequesting_userIsSet(boolean value) {
    if (!value) {
      this.requesting_user = null;
    }
  }

  public String getRole_name() {
    return this.role_name;
  }

  public TShowGrantRoleParams setRole_name(String role_name) {
    this.role_name = role_name;
    return this;
  }

  public void unsetRole_name() {
    this.role_name = null;
  }

  /** Returns true if field role_name is set (has been assigned a value) and false otherwise */
  public boolean isSetRole_name() {
    return this.role_name != null;
  }

  public void setRole_nameIsSet(boolean value) {
    if (!value) {
      this.role_name = null;
    }
  }

  public boolean isIs_admin_op() {
    return this.is_admin_op;
  }

  public TShowGrantRoleParams setIs_admin_op(boolean is_admin_op) {
    this.is_admin_op = is_admin_op;
    setIs_admin_opIsSet(true);
    return this;
  }

  public void unsetIs_admin_op() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_ADMIN_OP_ISSET_ID);
  }

  /** Returns true if field is_admin_op is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_admin_op() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_ADMIN_OP_ISSET_ID);
  }

  public void setIs_admin_opIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_ADMIN_OP_ISSET_ID, value);
  }

  public com.cloudera.impala.thrift.TPrivilege getPrivilege() {
    return this.privilege;
  }

  public TShowGrantRoleParams setPrivilege(com.cloudera.impala.thrift.TPrivilege privilege) {
    this.privilege = privilege;
    return this;
  }

  public void unsetPrivilege() {
    this.privilege = null;
  }

  /** Returns true if field privilege is set (has been assigned a value) and false otherwise */
  public boolean isSetPrivilege() {
    return this.privilege != null;
  }

  public void setPrivilegeIsSet(boolean value) {
    if (!value) {
      this.privilege = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REQUESTING_USER:
      if (value == null) {
        unsetRequesting_user();
      } else {
        setRequesting_user((String)value);
      }
      break;

    case ROLE_NAME:
      if (value == null) {
        unsetRole_name();
      } else {
        setRole_name((String)value);
      }
      break;

    case IS_ADMIN_OP:
      if (value == null) {
        unsetIs_admin_op();
      } else {
        setIs_admin_op((Boolean)value);
      }
      break;

    case PRIVILEGE:
      if (value == null) {
        unsetPrivilege();
      } else {
        setPrivilege((com.cloudera.impala.thrift.TPrivilege)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REQUESTING_USER:
      return getRequesting_user();

    case ROLE_NAME:
      return getRole_name();

    case IS_ADMIN_OP:
      return Boolean.valueOf(isIs_admin_op());

    case PRIVILEGE:
      return getPrivilege();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REQUESTING_USER:
      return isSetRequesting_user();
    case ROLE_NAME:
      return isSetRole_name();
    case IS_ADMIN_OP:
      return isSetIs_admin_op();
    case PRIVILEGE:
      return isSetPrivilege();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TShowGrantRoleParams)
      return this.equals((TShowGrantRoleParams)that);
    return false;
  }

  public boolean equals(TShowGrantRoleParams that) {
    if (that == null)
      return false;

    boolean this_present_requesting_user = true && this.isSetRequesting_user();
    boolean that_present_requesting_user = true && that.isSetRequesting_user();
    if (this_present_requesting_user || that_present_requesting_user) {
      if (!(this_present_requesting_user && that_present_requesting_user))
        return false;
      if (!this.requesting_user.equals(that.requesting_user))
        return false;
    }

    boolean this_present_role_name = true && this.isSetRole_name();
    boolean that_present_role_name = true && that.isSetRole_name();
    if (this_present_role_name || that_present_role_name) {
      if (!(this_present_role_name && that_present_role_name))
        return false;
      if (!this.role_name.equals(that.role_name))
        return false;
    }

    boolean this_present_is_admin_op = true;
    boolean that_present_is_admin_op = true;
    if (this_present_is_admin_op || that_present_is_admin_op) {
      if (!(this_present_is_admin_op && that_present_is_admin_op))
        return false;
      if (this.is_admin_op != that.is_admin_op)
        return false;
    }

    boolean this_present_privilege = true && this.isSetPrivilege();
    boolean that_present_privilege = true && that.isSetPrivilege();
    if (this_present_privilege || that_present_privilege) {
      if (!(this_present_privilege && that_present_privilege))
        return false;
      if (!this.privilege.equals(that.privilege))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_requesting_user = true && (isSetRequesting_user());
    builder.append(present_requesting_user);
    if (present_requesting_user)
      builder.append(requesting_user);

    boolean present_role_name = true && (isSetRole_name());
    builder.append(present_role_name);
    if (present_role_name)
      builder.append(role_name);

    boolean present_is_admin_op = true;
    builder.append(present_is_admin_op);
    if (present_is_admin_op)
      builder.append(is_admin_op);

    boolean present_privilege = true && (isSetPrivilege());
    builder.append(present_privilege);
    if (present_privilege)
      builder.append(privilege);

    return builder.toHashCode();
  }

  public int compareTo(TShowGrantRoleParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TShowGrantRoleParams typedOther = (TShowGrantRoleParams)other;

    lastComparison = Boolean.valueOf(isSetRequesting_user()).compareTo(typedOther.isSetRequesting_user());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequesting_user()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requesting_user, typedOther.requesting_user);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRole_name()).compareTo(typedOther.isSetRole_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRole_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.role_name, typedOther.role_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIs_admin_op()).compareTo(typedOther.isSetIs_admin_op());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_admin_op()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_admin_op, typedOther.is_admin_op);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrivilege()).compareTo(typedOther.isSetPrivilege());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrivilege()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.privilege, typedOther.privilege);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TShowGrantRoleParams(");
    boolean first = true;

    if (isSetRequesting_user()) {
      sb.append("requesting_user:");
      if (this.requesting_user == null) {
        sb.append("null");
      } else {
        sb.append(this.requesting_user);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("role_name:");
    if (this.role_name == null) {
      sb.append("null");
    } else {
      sb.append(this.role_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("is_admin_op:");
    sb.append(this.is_admin_op);
    first = false;
    if (isSetPrivilege()) {
      if (!first) sb.append(", ");
      sb.append("privilege:");
      if (this.privilege == null) {
        sb.append("null");
      } else {
        sb.append(this.privilege);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (role_name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'role_name' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'is_admin_op' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
    if (privilege != null) {
      privilege.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TShowGrantRoleParamsStandardSchemeFactory implements SchemeFactory {
    public TShowGrantRoleParamsStandardScheme getScheme() {
      return new TShowGrantRoleParamsStandardScheme();
    }
  }

  private static class TShowGrantRoleParamsStandardScheme extends StandardScheme<TShowGrantRoleParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TShowGrantRoleParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REQUESTING_USER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.requesting_user = iprot.readString();
              struct.setRequesting_userIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ROLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.role_name = iprot.readString();
              struct.setRole_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_ADMIN_OP
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_admin_op = iprot.readBool();
              struct.setIs_admin_opIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PRIVILEGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.privilege = new com.cloudera.impala.thrift.TPrivilege();
              struct.privilege.read(iprot);
              struct.setPrivilegeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetIs_admin_op()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'is_admin_op' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TShowGrantRoleParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.requesting_user != null) {
        if (struct.isSetRequesting_user()) {
          oprot.writeFieldBegin(REQUESTING_USER_FIELD_DESC);
          oprot.writeString(struct.requesting_user);
          oprot.writeFieldEnd();
        }
      }
      if (struct.role_name != null) {
        oprot.writeFieldBegin(ROLE_NAME_FIELD_DESC);
        oprot.writeString(struct.role_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_ADMIN_OP_FIELD_DESC);
      oprot.writeBool(struct.is_admin_op);
      oprot.writeFieldEnd();
      if (struct.privilege != null) {
        if (struct.isSetPrivilege()) {
          oprot.writeFieldBegin(PRIVILEGE_FIELD_DESC);
          struct.privilege.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TShowGrantRoleParamsTupleSchemeFactory implements SchemeFactory {
    public TShowGrantRoleParamsTupleScheme getScheme() {
      return new TShowGrantRoleParamsTupleScheme();
    }
  }

  private static class TShowGrantRoleParamsTupleScheme extends TupleScheme<TShowGrantRoleParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TShowGrantRoleParams struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.role_name);
      oprot.writeBool(struct.is_admin_op);
      BitSet optionals = new BitSet();
      if (struct.isSetRequesting_user()) {
        optionals.set(0);
      }
      if (struct.isSetPrivilege()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRequesting_user()) {
        oprot.writeString(struct.requesting_user);
      }
      if (struct.isSetPrivilege()) {
        struct.privilege.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TShowGrantRoleParams struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.role_name = iprot.readString();
      struct.setRole_nameIsSet(true);
      struct.is_admin_op = iprot.readBool();
      struct.setIs_admin_opIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.requesting_user = iprot.readString();
        struct.setRequesting_userIsSet(true);
      }
      if (incoming.get(1)) {
        struct.privilege = new com.cloudera.impala.thrift.TPrivilege();
        struct.privilege.read(iprot);
        struct.setPrivilegeIsSet(true);
      }
    }
  }

}

